version: '3'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production node server.js
    volumes:
      - .\app:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - 13000:3000
    # command: bash
    command: sh -c 'npm ci; node server.js'
    tty: true

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   ports:
  #     - 4040:4040
  #   volumes:
  #     - .\ngrok.yml:/etc/ngrok.yml
